[build-system]
requires = ["setuptools>=40.8.0", "wheel", "pegen"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ['py38']

[tool.isort]
atomic=true
force_grid_wrap=0
include_trailing_comma=true
multi_line_output=3
not_skip="__init__.py"
use_parentheses=true
